### PR TITLE
adds simple argument to properties function

### PR DESCRIPTION
**Pull request by chapmandu**
when used `myobject.properties(simple=true)` will recurse through an object, it's nested properties and return a structure of simple values. It is most useful when using `dump` to visually render an object.

### CODE REVIEW

**Comment by perdjurner** [comment]
I'm getting a test error on one of the servers.

I think it's because you're using SerializeJSON and sometimes the order comes out different, see below:

assert failed: SerializeJSON(loc.in) eq SerializeJSON(loc.want)

SerializeJSON(loc.in) = '{"FIRSTNAME":"adam","POST":{"VIEWS":1000,"BODY":"This is the single body","AVERAGERATING":1.0,"TITLE":"this is the single title"},"POSTS":[{"VIEWS":2000,"BODY":"This is the arrays first body","AVERAGERATING":2.0,"TITLE":"this is the arrays first title"},{"VIEWS":3000,"BODY":"This is the arrays second body","AVERAGERATING":3.0,"TITLE":"this is the arrays second title"}],"LASTNAME":"chapman"}'

SerializeJSON(loc.want) = '{"POST":{"VIEWS":1000,"BODY":"This is the single body","AVERAGERATING":1.0,"TITLE":"this is the single title"},"FIRSTNAME":"adam","POSTS":[{"VIEWS":2000,"BODY":"This is the arrays first body","AVERAGERATING":2.0,"TITLE":"this is the arrays first title"},{"VIEWS":3000,"BODY":"This is the arrays second body","AVERAGERATING":3.0,"TITLE":"this is the arrays second title"}],"LASTNAME":"chapman"}'

Can you correct the test?

**Comment by chapmandu** [comment]
Sure, I can correct the test.. Which CF engine was it?

**Comment by perdjurner** [comment]
ACF 10 I think:

https://travis-ci.org/cfwheels/cfwheels/builds/119738957

**Comment by perdjurner** [comment]
Still some kind of error...

http://zebrinny.viviotech.net/index.cfm?controller=wheels&action=wheels&view=tests&type=core

**Pull request merged**
