### PR TITLE
Issue 575 extend sendEmail

### PR DESCRIPTION
**Pull request by chapmandu**
https://github.com/cfwheels/cfwheels/issues/575

### CODE REVIEW

**Comment by chapmandu** [comment]
On review, I'm thinking the detectMultipart argument is kinda redundant now. When it's set to false it introduces an unnecessary assumption about the body type.

**Comment by perdjurner** [comment]
I can't find any clear explanation anywhere about what this pull request does.

Can you post that here or on the issue?

Thanks.

**Comment by neokoenig** [comment]
Related to https://github.com/cfwheels/cfwheels/issues/575

**Comment by perdjurner** [comment]
I know, just wasn't clear to me in there either (what has been done so far and what is still being discussed I mean).

**Comment by neokoenig** [comment]
Sorry @perdjurner : to be more specific:

1) sendMail returns a struct with the generated HTML and Plain text where possible; 
i.e
```
mymail= sendEmail(
        from="service@yourwebsite.com",
        to=member.email,
        template="myemailtemplateHTML,myemailtemplatePLAIN",
        subject="Thank You for Becoming a Member",
        recipientName=member.name,
        startDate=member.startDate
    );
```
returns
```
mymail.html="<p>stufff</p>";
mymail.plain="stufff";
```

it should return `html` and `plain` irrespective of whether both templates are used or not.

2) sendMail can write contents to a physical file
```
 sendEmail(
        from="service@yourwebsite.com",
        to=member.email,
        template="myemailtemplate",
        subject="Thank You for Becoming a Member",
        recipientName=member.name,
        startDate=member.startDate,
        writeToFile="foo.txt"
    );
```
will write that to a foo.txt instead of returning a struct

3) "deliver" argument now accessible and not just internal

Won't send:
```
 sendEmail(
        from="service@yourwebsite.com",
        to=member.email,
        template="myemailtemplate",
        subject="Thank You for Becoming a Member",
        recipientName=member.name,
        startDate=member.startDate,
       deliver=false
    );
```

Does that help?

**Comment by perdjurner** [comment]
Yes, thanks, I'll post my thoughts on the issue.

**Comment by chapmandu** [comment]
Thanks Tom & Per.. The only thing I have to add to Tom's comments are that the 2 additional structure keys returned are html and text (not plain) this is keeping in line with the cfmail type argument.

**Comment by chapmandu** [comment]
Oh, and the structure is always returned.

**Comment by perdjurner** [comment]
Excellent.

**Comment by neokoenig** [comment]
Reopening to document

**Pull request merged**
