### PR TITLE
Uses the X-Forwarded-Proto header if it exists to set the protocol to…

### PR DESCRIPTION
**Pull request by bpamiri**
Modify the isSecure() function in wheels/controller/miscellaneous.cfm to use the cgi.http_x_forwarded_proto header if it exists in determining the protocol to use. Then modified a couple of instances that use cgi scripts directly to use isSecure() to determine what protocol to use.

### CODE REVIEW

**Comment by chapmandu** [comment]
Thanks! Be sure to add a line to the changelog.md

**Comment by neokoenig** [comment]
I've not used this header at all. Happy to leave it up to @chapmandu

**Comment by bpamiri** [comment]
I moved http_x_forwarded_for and http_x_forwarded_proto into $cgiScope and refactored so the two are referenced from the request scope.

**Comment by bpamiri** [comment]
> Thanks! Be sure to add a line to the changelog.md

I've brought this branch up to date and modified the changelog. This should make it easier to merge once approved.

**Comment by chapmandu** [comment]
Merged! Thanks for the PR and the changes.. 👍

**Pull request merged**
