### PR TITLE
Html compress format - invalid coldfusion function

### PR DESCRIPTION
**Pull request by michaeldiederich**
The function `HtmlCompressFormat()` is no valid coldfusion function and throws an exception.

### CODE REVIEW

**Comment by neokoenig** [comment]
Hi Michael; Is this related to this? https://github.com/cfwheels/cfwheels/issues/883

**Comment by michaeldiederich** [comment]
Hi Tom, well the commit history yes, the change is not related. If you run a test with junit, the undefinied function `htmlCompressFormat()` is called. I should delete my fork and create a new branch for the next pull request.

**Comment by michaeldiederich** [comment]
Any more questions about my merge request?

**Comment by neokoenig** [comment]
Looks like HtmlCompressFormat() is from https://cflib.org/udf/HtmlCompressFormat - quite *why* it's there I have no idea. I thought it might have something to do with our windows test box, but I can't see any further references to it. @chapmandu can  you confirm?  I think you did something with the junit code at some point?

**Comment by chapmandu** [comment]
It just compressed the junit XML output. It’s not really needed..

Regards,
Adam

**Comment by neokoenig** [comment]
Great thanks! Merging...

**Pull request merged**
