### PR TITLE
Richtext option for TextArea()

### PR DESCRIPTION
**Pull request by reubenbrown13**
I have added an option in the textArea() function to use ckEditor5 for a basic rich text editor.  The CDN to use is set in the setting.cfm file so it can be updated and changed per user's needs.  The script may need to be loaded in another file other than wheels/styles/header if you are using the example-app as your starting point.

### CODE REVIEW

**Comment by reubenbrown13** [comment]
Also added a fix for the output issue in the onError file.  Not pretty, but is functional and fixes issues #901 and #848

**Comment by neokoenig** [comment]
Hi Reuben; thanks for your enthusiasm - however, we've got a policy of not including any 3rd party Javascript dependencies into the core: this is perhaps something more suited to a plugin? As a side note, for pull requests it's great if the pull requests can only be related to one issue! I'd encourage you to create a gitHub issue first wherever possible - for instance, we could have saved you some time by saying the CKEditor changes weren't appropriate.

**Comment by reubenbrown13** [comment]
Ahhh... understand... .I had to add a richtext option for a project I am working on anyway.  I will take a look at what it takes to integrate it as a plugin.

**Comment by reubenbrown13** [comment]
I took your advice and ripped out the code and set it up as a plugin.  I need to get it loaded on forgebox, but if you want direct access, here is my repo : https://github.com/reubenbrown13/cfwheels-ckEditor-plugin

**Comment by reubenbrown13** [comment]
this pull needs to be omitted per the guideline for integrating this as a plugin.

**Pull request closed without merging**
