### PR TITLE
Make test suite functional on m1 mac

### PR DESCRIPTION
**Pull request by bpamiri**
This is a work in progress.

I'm working on getting the test suite to run on an M1 Mac. I'm taking the approach to use the latest versions of docker images till that path works then lock down the versions to the tested version so we don't get bug creep due to an image updating. This is the status of the matrix so far:

- [x] Lucee5 - H2
- [x] Lucee5 - Postgres
- [x] Lucee5 - MySQL
- [x] Lucee5 - SQLServer
- [x] Adobe2016 - Postgres
- [x] Adobe2016 - MySQL
- [x] Adobe2016 - SQLServer
- [x] Adobe2018 - Postgres
- [x] Adobe2018 - MySQL
- [x] Adobe2018 - SQLServer
- [x] Expose Debug info in a failed test result

### CODE REVIEW

**Comment by bpamiri** [comment]
So I got MySQL working for Lucee. There are now official MySQL images available for arm64 but they are Oracle 8.0 flavor. I had a few test that failed on Lucee with the new data base but when I looked at Adobe 2016 it was another story. It runs like a dog, in the 10 minute time frame to complete the test suite and when it does a set of the tests fail all with JSON serialization issues. I'm taking a break from this for a while to assess how to move forward. I could look at MariaDB instead but that may bring it's own set of issues. I also think we need to look at Adobe 2021 at some point so that may play nicer with MySQL 8.0 but who knows. Like I said, it's time to step away from this to get some clarity.

**Comment by bpamiri** [comment]
I have all the tests passing on a Mac M1. This is also running the latest MySQL 8.0. @adamzenu and @neokoenig can you guys run this on a windows box to see if it runs properly. If you don't get a chance no worries, I'll fire up a windows box on Monday and test this.

**Comment by bpamiri** [comment]
[screencapture-localhost-3000-2022-07-08-13_59_47.pdf](https://github.com/cfwheels/cfwheels/files/9075018/screencapture-localhost-3000-2022-07-08-13_59_47.pdf)

**Comment by chapmandu** [comment]
I can test it on Linux.. but I don't have any Windows machines. Proudly 9 years free.. ;)

**Comment by bpamiri** [comment]
I was able to run the full test suite on my Intel based MacBook Pro. I think we are good. I'll still try to run it on a fresh windows box to make sure nothing else pops up.

**Comment by bpamiri** [comment]
Adam Linux will work too. I just want to make sure I didn’t break it on other platforms just trying to get the Mac M1 working. This does update the structure of the files, updates MySQL to 8.0, uses the latest Linux based Azure SQL Server, and many other updates to how the docker-compose, dokerfile, server.json, and cfconfig for each platform is defined. So it’s a major modernization of the toolset.

**Comment by chapmandu** [comment]
Linux (Linux Mint 20.3 : Kernel 5.4.0-121-generic)

image

**Comment by bpamiri** [comment]
Thanks for running these Adam. @chapmandu

**Comment by chapmandu** [comment]
Should you have major supported versions of db engines? eg: mysql56, mysql57, mysql8.. we are still on mysql 5.6..

**Comment by bpamiri** [comment]
yes, that makes sense. I would also like to add support for ACF 2021. And perhaps a way to test against bleeding edge releases of engines and DBs so we can get a heads up when a new release may effect us. I have Lucee 6 in mind here. 

All in all, I think this PR is just the beginning of this process and not the end. I wanted to use this PR as a means for me to become more familiar with the testing suite and be able to run the test suite on my personal device so I could feel more comfortable tackling some of the low hanging fruit in the issues list. 

Next up would be looking at the GitHub Actions and getting them to run the way we need and perhaps incorporating the larger matrix into them.

**Comment by chapmandu** [comment]
Are you planning to merge this?

**Comment by chapmandu** [comment]
Are you planning on merging this?

**Pull request closed without merging**
