### PR TITLE
Invalid column not throwing exception in select argument

### PR DESCRIPTION
**Pull request by zainforbjs**
Added an exception in case the column specified in the select or group argument passed in the findAll() function does not exist in the database.

### CODE REVIEW

**Review by bpamiri — APPROVED** [review]
Thanks

**Comment by bpamiri** [comment]
Closes #591

**Review by bpamiri — CHANGES_REQUESTED** [review]
@zainforbjs this is breaking on columns added via a class property as in calculated or aliased columns. Do a search for firstID and you'll see it is defined as a property on the Post model but is getting caught by this exception because the column doesn't exist in the DB.

**Comment by zainforbjs** [comment]
@bpamiri Added some conditions to fix the 6 test cases that were failing. Added details in the commit.

**Review by bpamiri — APPROVED** [review]

**Pull request merged**
