### PR TITLE
extra checks to make sure we have everything we need to grab the csrf…

### PR DESCRIPTION
**Pull request by liferealized**
… auth token

### CODE REVIEW

**Comment by liferealized** [comment]
@chrisdpeters lets see if it fails the build now

**Comment by liferealized** [comment]
Unfortunately I'm still at a loss for why this was happening. My only thinking is that something changed for csrf while the testing server is running like the secret key. Then, when it goes to decrypt the cookie, it fails and decrypt returns the encrypted string instead of throwing an error of some sort.

**Comment by neokoenig** [comment]
Well, it just passed!

**Comment by chrisdpeters** [comment]
My sense has been that it's some sort of race condition unique to testing. Glad that the fix appears to have fixed it. I'll have to pull that back into the plugin and see how it affects our production environments. (You know, if I want to have a _really fun_ week sometime. ;))

**Comment by liferealized** [comment]
Always test in production... isn't that what they say?

**Pull request merged**
