### PR TITLE
Added afterFind callback hook in the findAll function in case of structs

### PR DESCRIPTION
**Pull request by zainforbjs**
Added callback for Afterfind in function $serializeQueryToStructs in the file wheels/model/serialize.cfm. The afterFind hook was not being called when findAll(returnAs = 'struct') is used on the model. This was working when returntype is query or object but not when it is struct.

### CODE REVIEW

**Comment by bpamiri** [comment]
Closes #605

**Comment by bpamiri** [comment]
@zainforbjs Can you merge the latest Develop code into this branch and look at the tests. All the core tests are failing on this when run in the local Docker test suite.

**Comment by zainforbjs** [comment]
@bpamiri Sure, I am on it.

**Comment by zainforbjs** [comment]
@bpamiri The PR is good to go for merge. please confirm. thanks

**Comment by bpamiri** [comment]
Thanks Zain.

**Pull request merged**
