### PR TITLE
Upgrade plugins to allow multiple override methods

### PR DESCRIPTION
**Pull request by liferealized**
Enhancement to wheels to solve #682

### CODE REVIEW

**Comment by perdjurner** [comment]
Looks great!

I'll look at merging this in soon.

**Comment by liferealized** [comment]
Thanks Per! If you have any questions, I'm available.

**Comment by perdjurner** [comment]
@neokoenig Help... again... can you kick the server?

**Comment by neokoenig** [comment]
it passed?

**Comment by neokoenig** [comment]
Oh no it didn't
(pantomime style)

**Comment by neokoenig** [comment]
Found a couple of CF10 specific syntax issues, but still getting (different) errors. Getting there though.

**Comment by neokoenig** [comment]
Chain Return Values from multiple plugin overrides + Chain Return Values from multiple plugin overrides in dispatch both failing in CF10

**Comment by neokoenig** [comment]
Odd, as this is passing locally for me on lucee4 / CF10 with MySQL

**Comment by neokoenig** [comment]
@liferealized Found the issue, but haven't had time to fix.

On ACF on the test box (on both CF10 + CF11) the result from `Chain Return Values from Multiple Plugin Overrides` and  `Chain Return Values from Multiple Plugin Overrides in dispatch` returns `/index.cfm?controller=wheels&action=wheels&urlfor01&urlfor02`, whereas the test is looking for the specific string `&urlfor02&urlfor01` (i.e, the order is wrong).

Now, why it's doing this I have no idea, but it could be something IIS related maybe?

**Comment by liferealized** [comment]
The only thing it could be is if those instances are loading plugins OR running through plugin in a different order. This would be happening in Plugins.cfc. The `$pluginFolders()` method would be the likely target for optimization. I would add a sort to the `DirectoryList()` call AND to the QoQ directly after.

I'll put another patch together and get it over to you.

**Comment by liferealized** [comment]
Well, after having a further look, the sorting only really matters when mixins are built. Patch coming...

**Comment by liferealized** [comment]
Hopefully #687 should help resolve your issue. I really appreciate your help with testing this.

**Comment by neokoenig** [comment]
Cool, that's passing, I'll merge it - thanks!!

**Comment by perdjurner** [comment]
I wish pull requests would run tests on all servers. That would really help eh? Unfortunately, I don't know nearly enough about Travis to fix that.

**Comment by neokoenig** [comment]
They do? https://travis-ci.org/cfwheels/cfwheels/builds/180069831

**Comment by neokoenig** [comment]
OH no they don't (pantomime again)

**Comment by neokoenig** [comment]
Yep, still failing on 

runner	Chain return values from multiple plugin overrides	31	Failure
assert failed: valid neq 0
valid = 0
runner	Chain return values from multiple plugin overrides in dispatch	31	Failure
assert failed: valid neq 0
valid = 0

The only reason I worked out it was the order was by running the tests manually on the CF10 box and debugging the output

**Comment by liferealized** [comment]
Good news. My fix from this morning was wrong and I've been able to reproduce the error so a fix should be coming soon.

**Comment by neokoenig** [comment]
Top stuff

**Comment by liferealized** [comment]
#688 should do it. sorry for all the confusion

**Comment by neokoenig** [comment]
Yay, all passed - thanks @liferealized !

**Comment by neokoenig** [comment]
NB: Need to add to changelog + document

**Comment by liferealized** [comment]
Yup. I can update the changelog in the AM. Where do I go to update documentation?

**Comment by neokoenig** [comment]
http://docs.cfwheels.org/ - then select `2.0` from the dropdown, navigate to the page you want and do suggest edits. Alternatively if you want to pencil something here I can port it across.

**Comment by liferealized** [comment]
#689 has the changelog update

**Comment by neokoenig** [comment]
Leaving open to document

**Pull request merged**
