### PR TITLE
Add support for Oracle DB

### PR DESCRIPTION
**Pull request by abejenaru**
~~Compatible with and tested on~~ Developed for Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 / Adobe CF11.
Used in Production.
Pagination support (limit / offset statements) not implemented.
No test suite.

### CODE REVIEW

**Comment by neokoenig** [comment]
This is fantastic - just a reminder we don't have oracle in our test Travis setup anymore (it was tied to our CF10 installation) - so this is something which will need to caveat if we're putting support back in the core for it!

**Comment by abejenaru** [comment]
IMO it should be treated as experimental, yet made available to everybody willing to use it (and hopefully help it mature).

**Comment by neokoenig** [comment]
> IMO it should be treated as experimental, yet made available to everybody willing to use it (and hopefully help it mature).

What held us back last time was that Oracle was in our CI testing env, and there were failing tests which we didn't have the time/knowledge/skills to fix at hand. This was further exacerbated by moving database migrations into the core; don't suppose it's on your list to add an adapter in `wheels/migrator/adapters`? :)

**Comment by shutterassault** [comment]
> IMO it should be treated as experimental, yet made available to everybody willing to use it (and hopefully help it mature).

Definitely willing to help test this. I still need to use Oracle at work and stuck on Wheels 1.4.5.  We are on 11.2 as well and CF 2016. Unfortunately don't have a time of time, but can help out if there's a basic task list. I do remember working on the migration adapter before all the files went to the cfscript style. Not sure if there's anything useful in there anymore. I don't use the migrations. It would be great just to get the basic functionality even.

**Comment by abejenaru** [comment]
> What held us back last time was that Oracle was in our CI testing env, and there were failing tests which we didn't have the time/knowledge/skills to fix at hand. This was further exacerbated by moving database migrations into the core; don't suppose it's on your list to add an adapter in `wheels/migrator/adapters`? :)

Oh snap, not really, I'm working with a pre-existing database! Even more bad news, this is probably one of the last CF projects here, so I'm mostly putting the adapter out here as it is...

**Comment by neokoenig** [comment]
Since we've not got Oracle in our CI setup anymore, it shouldn't prevent us from moving forward in the future I guess. The danger is that it's just a second class citizen!

if you're interested, these are the relevant commits removing previous code:
https://github.com/cfwheels/cfwheels/commit/46afd5ddc700929a39ac23e1ae5ceb56079d7781
https://github.com/cfwheels/cfwheels/commit/366db12173702f091bcb93d09e391de67bda3475

**Comment by chapmandu** [comment]
@neokoenig Where are we at with this?

**Comment by neokoenig** [comment]
@chapmandu Same as before, in that Oracle would be a second class citizen (no DB migrations) and we've no real expertise  / testing environment for it. I'm happy enough to add this back in principle as long as it doesn't create issues like before, and is supplied on an "as is" basis...

**Comment by chapmandu** [comment]
Agreed.

**Comment by chapmandu** [comment]
Shall we make this part of 2.2?

**Comment by neokoenig** [comment]
Yes, push to 2.2, and marked as unsupported. I've no issues with Oracle support where we can provide it, but it needs people who are using it to contribute.

**Comment by chapmandu** [comment]
@abejenaru  Can you please add an entry into the changelog under 2.2 and we'll get this bad boy merged..

**Pull request merged**
