### PR TITLE
#986 Auto-reload-test-framework-html

### PR DESCRIPTION
**Pull request by chapmandu**

### CODE REVIEW

**Comment by neokoenig** [comment]
Yeah alright - don't see why not. Shouldn't go into 2.1 proper, but happy for it to go into next point release.

**Comment by chapmandu** [comment]
@neokoenig By that you mean 2.2? I've added it to this section of the changelog

**Comment by chapmandu** [comment]
BTW, I used it all day yesterday for TDD.. Works very nicely.

**Comment by neokoenig** [comment]
Yes 2.2; Also lol @ you marking this as "Good first issue" and then just immediately doing it yourself.

**Pull request merged**
