### PR TITLE
Add Adobe 2021 Support to local Docker testing

### PR DESCRIPTION
**Pull request by bpamiri**
This PR complete some work on the rearchitecture of the configuration files used for the individual docker images for local testing.

The test suite now tests 
Lucee 5 (MySQL, SQL Server, PostgreSQL, H2)
Lucee 6 (MySQL, SQL Server, PostgreSQL, H2)
Adobe 2016 (MySQL, SQL Server, PostgreSQL)
Adobe 2018 (MySQL, SQL Server, PostgreSQL)
Adobe 2021 (MySQL, SQL Server, PostgreSQL)

Once other major feature that was completed in this PR is that the local web images properly load the files from the host machine which makes it easier to do local development and have changes reflected in the docker images immediately without requiring any commenting and uncommenting lines in the dockerfile or having to rebuild the images between each cycle.

### CODE REVIEW

**Comment by chapmandu** [comment]
Great work!

**Comment by bpamiri** [comment]
> Great work!

Thanks. This is fully functional for local development with live code reload into each container. The Adobe 2021 test suite is failing in GitHub Actions. Still looking into getting that working before integrating this into dev.

**Comment by bpamiri** [comment]
This finally working. Adobe 2021 is tested against MySQL, SQL Server, and PostgreSQL. Both the GitHub actions tests are passing as well as all local Docker based tests. If using the local Docker tests the code is injected into each VM so the VMs will get the live code updates.

**Comment by chapmandu** [comment]
Well done! 🔥

**Pull request merged**
