### PR TITLE
Fix for postgres and cfxx

### LINKED ISSUE #699: Postgres adapter needs some love
After getting commandbox setup and running all versions of servers against the latest wheels test with a postgres DB, there are around 50 errors that happen.

I'm creating this issue to start to dig in and figure out what is going on.

### PR DESCRIPTION
**Pull request by liferealized**
Fixes #699

### CODE REVIEW

**Comment by liferealized** [comment]
@neokoenig  thanks for the commandbox suggestion, it's amazing!

**Comment by neokoenig** [comment]
PS, don't forget to try out `install cfwheels-cli` :)
(although lots of work to do on that yet)

**Comment by liferealized** [comment]
@chrisdpeters this build has failed due to csrf stuff again. Would you like me to look into this?

**Comment by chrisdpeters** [comment]
@liferealized If you'd like. Due to limited time, I really only test locally against Lucee 5 and Postgres. It seems to run consistently fine on that combo.

**Comment by chrisdpeters** [comment]
P. S. A couple tests from the new plugin lookup seem to fail consistently for me on Lucee 5.1 + Linux. I should probably create an issue for that.

**Comment by neokoenig** [comment]
Ugh, weird. getting https://github.com/cfwheels/cfwheels/issues/631 on CF10 now. Why the hell has that magically started showing up?
The SCALE parameter to the $getType function is required but was not passed in.

**Pull request merged**
