### PR TITLE
Fix params bug in CLI API

### PR DESCRIPTION
**Pull request by bpamiri**
This PR fixes a bug in the API used by the CLI to pass commands to the server. The wheels > public > views > cli.cfm file used the params structure directly but that struct doesn't exist. I've modified the calls to `params` to call `request.wheels.params` instead.

### CODE REVIEW

**Comment by chapmandu** [comment]
@bpamiri This PR is not showing that any files have changed. What am I missing?

**Comment by bpamiri** [comment]
@chapmandu you weren't missing anything. I on the other hand am missing half a brain. The intended change is now included in the PR. Sorry for the confusion.

**Review by chapmandu — CHANGES_REQUESTED** [review]
Could you leave the indenting intact. I believe there's an .editorconfig file that should help keep standards applied.

**Comment by chapmandu** [comment]
@neokoenig Whilst Peter's solution seems to fix the symptom, why would params scope not be available in this view?

**Comment by neokoenig** [comment]
> @neokoenig Whilst Peter's solution seems to fix the symptom, why would params scope not be available in this view?

IIRC, there's something weird about the way the public cfc is created; basically it doesn't go through the whole wheels controller cycle ( because it can't, otherwise it would interfere with the main app).

Looking at https://github.com/cfwheels/cfwheels/blob/master/wheels/public/includes.cfm#L98 it sure looks like I hit the same issue when doing the rest of the GUI. I'm just trying to work out how wheels/public/views/cli.cfm worked at all, ever. Cos it did at some point.

**Pull request merged**
